<font color = 'blue'>

# A Project for Numerical Analysis Course by Prof. Saeed Kazem

## Kiarash Geraili, Computer Science student at Amirkabir University of Technology

### STD Num: 9413027 
### Spring, 2020

</font>


# Code Section

In [9]:
import numpy as np
#################################################
#Defining norm-2, known as  euclidean norm 

def norm_2(v):
    sum = 0

    for i in range(len(v)):
        sum = sum + (v[i]**2)
        
    return (sum**0.5)
#################################################
#Defining e_i = u_i / ||u_i|| vectors

def e_i(u):
    
    x = u / norm_2(u)
    return x
##################################################
#Defining QR decomposition using Grahm-Shmit approach

def QR_GS(A):
    n = len(A)

    u = np.zeros((n,n))

    u = np.array(u)

    Sum = 0 
  
    for i in range(n):

        Sum = 0
        for j in range(i):
            
            Sum = Sum + (A[:,i] @ e_i(u[j,:])) * e_i(u[j,:])           
     
        u[i,:] = A[:,i] - Sum
        
    Q = np.zeros((n,n))
    R = np.ones((n,n))

    for i in range(n):
        Q[:,i] = e_i(u[i,:])
    for i in range(n):
        for j in range(n):
            if j < i:
                R[i][j] = 0
            else:
                R[i][j] = A[:,j]@e_i(u[i,:])
    return Q,R
###########################################################
# Main Code:

#Giving number of dots and degree of fitting function from user
m = int(input("Enter the number of spots: "))
n = int(input("Enter the degree of fitting function + 1: "))

#Check out that does degree of function is lower than number of spots
#if it does not, so Exit

if m < n:
    print("Error: n is greater than m which is invalid!")
    exit

#Initializing dynamic list for saving spots
x_List = []
y_List = []

#Getting all the spots from user
for i in range(m):
    x_List.append(float(input("Enter the x of spot " + str(i) + ":"))) #initiating x's
    y_List.append(float(input("Enter the y of spot " + str(i) + ":"))) #initiating y's

#AS the spots are fixed, now we change our data structure to vectors and matrixes to work with them easily
X = np.array(x_List)
Y = np.array(y_List)

temp = 0

#Defining zero matrix for initializing matrix A and vector B
B = np.zeros(n)
A = np.zeros((n,n))

#Creating matrix A
for i in range(n):
    
    for j in range(n):
        temp = 0 
        for k in range(m):            
            temp = temp + X[k]**(j + i)
        A[i][j]=temp         

#Creating Matrix B
for i in range(n): 
    temp=0
    for k in range(m):
        temp = temp + Y[k]*(X[k]**i)
    B[i]=temp
       
print("A Matrix is: ") 
print(A)
print("B Matrix is: ")
print(B)

#QR decomposition for matrix A, using defined function
Q,R = QR_GS(A)

print("Q Matrix is: ")
print(Q)
print("R Matrix is: ")
print(R)

#Finding reverse of R
R_inv = np.linalg.inv(R)

#Finding transpose of Q
Q_t = Q.transpose

#Solving equation by multiplying R inverse to Q transpose to Vector B and print the result
print("The Coefficients of Polynomial is: ")
print(R_inv@Q_t()@B)

# notice that as an instance, we solve the example that teacher solves in our textbook:

# Given spots: (0,1),(1,1.1),(2,1.5) we want to fit a linear function
# As you can see the result of code is the same as the result of solved example in textbook
# Trivially you can test the code using other spots and the fitting degree

Enter the number of spots: 3
Enter the degree of fitting function + 1: 2
Enter the x of spot 0:0
Enter the y of spot 0:1
Enter the x of spot 1:1
Enter the y of spot 1:1.1
Enter the x of spot 2:2
Enter the y of spot 2:1.5
A Matrix is: 
[[3. 3.]
 [3. 5.]]
B Matrix is: 
[3.6 4.1]
Q Matrix is: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
R Matrix is: 
[[4.24264069 5.65685425]
 [0.         1.41421356]]
The Coefficients of Polynomial is: 
[0.95 0.25]


# Evaluating Section

In [10]:
#In order to evaluate our QR decomposition code
#Here we use built-in functions to see that
#Does our result matches or not?

import numpy as np

A = [[3,3],[3,5]]
B = [3.6,4.1]

A = np.array(A)
B = np.array(B)

Q,R = np.linalg.qr(A)

print("Q Matrix is: ")
print(Q)
print("R Matrix is: ")
print(R)

x = np.linalg.solve(A, B)
print("X Matrix is: ")
print(x)

Q Matrix is: 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R Matrix is: 
[[-4.24264069 -5.65685425]
 [ 0.          1.41421356]]
X Matrix is: 
[0.95 0.25]
